### ISSUE TITLE
Security Alert IE11

### ISSUE THREAD

**Issue by davidkelley** [dhoer/choco-selenium#19]
Hi, when testing a HTTPS URL in IE11 on Windows Server 2016, I'm getting a Security Alert with the content "you are about to view pages over a secure connection" which I believe is crashing the driver. I've also executed the IE configuration script beforehand.

When testing a normal HTTP location, it's working fine.

I was wondering if there is a specific registry key which needs to be configured to disable this popup?

**Comment by dhoer** [comment]
It looks like that can be resolved with the following setting:

    ; Disable Internet Explorer "You are about to view pages over a secure connection" prompt
    [HKEY_CURRENT_USER\Software\Microsoft\Windows\Curre ntVersion\Internet Settings] WarnOnZoneCrossing"=dword:00000000

I will try to get an update to ie config out this weekend.

**Comment by dhoer** [comment]
@davidkelley any feedback on the script. I would like to see if it fixed your issue before merging it to master

**Comment by dhoer** [comment]
No feedback

**Comment by davidkelley** [comment]
Apologies, I never saw your original comment.

When installing choco-selenium on AWS EC2 Windows Server 2012/2016, the
security modal would popup, I've since resolved this with the following
command:

```
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings"
/v WarnonZoneCrossing /d "0" /t REG_DWORD /f
```

This works for both IE10 & IE11.
